// Generated by CoffeeScript 1.6.3
(function() {
  var SlideHeader,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  this.SlideHeader = SlideHeader = (function() {
    function SlideHeader(selector, options) {
      this.onScroll = __bind(this.onScroll, this);
      this.mouseMove = __bind(this.mouseMove, this);
      this.last = 0;
      this.shown = true;
      this.height = selector.getBoundingClientRect().height;
      this.supports3d = (selector.style["transform"] != null) || (selector.style["-webkit-transform"] != null) || (selector.style["-moz-transform"] != null);
      this.options = {
        speed: (options != null ? options.speed : void 0) || "300ms",
        selector: selector,
        mouseTrigger: (options != null ? options.mouseTrigger : void 0) || true
      };
      this.setStyle();
      window.onscroll = this.onScroll;
      if (this.options.mouseTrigger) {
        window.onmousemove = this.mouseMove;
      }
    }

    SlideHeader.prototype.destroy = function() {
      this.showHeader();
      window.onmousemove = null;
      return window.onscroll = null;
    };

    SlideHeader.prototype.setStyle = function() {
      var style;
      style = this.options.selector.style;
      style.position = "fixed";
      style.top = "0px";
      style.left = "0px";
      style.transition = "transform " + this.options.speed + ", top " + this.options.speed;
      style.webkitTransition = "-webkit-transform " + this.options.speed + ", top " + this.options.speed;
      return style.mozTransition = "-moz-transform " + this.options.speed + ", top " + this.options.speed;
    };

    SlideHeader.prototype.mouseMove = function(e) {
      if (this.shown) {
        return;
      }
      if (e.pageY - window.pageYOffset < this.height * 1.4) {
        return this.showHeader();
      }
    };

    SlideHeader.prototype.onScroll = function(e) {
      if (this.last + 100 > (new Date).getTime() || window.pageYOffset < 0) {
        return;
      }
      this.last = (new Date).getTime();
      if (window.pageYOffset > this.scrollYPosition) {
        this.hideHeader();
      } else {
        this.showHeader();
      }
      return this.scrollYPosition = window.pageYOffset;
    };

    SlideHeader.prototype.hideHeader = function() {
      var style;
      if (!this.shown) {
        return;
      }
      this.shown = false;
      style = this.options.selector.style;
      if (this.supports3d) {
        style["transform"] = "translate3d(0, -" + this.height + "px, 0)";
        style["-webkit-transform"] = "translate3d(0, -" + this.height + "px, 0)";
        return style["-moz-transform"] = "translate3d(0, -" + this.height + "px, 0)";
      } else {
        return this.options.selector.style.top = "-" + this.height + "px";
      }
    };

    SlideHeader.prototype.showHeader = function() {
      var style;
      if (this.shown) {
        return;
      }
      this.shown = true;
      style = this.options.selector.style;
      if (this.supports3d) {
        style["transform"] = "translate3d(0, 0px, 0)";
        style["-webkit-transform"] = "translate3d(0, 0px, 0)";
        return style["-moz-transform"] = "translate3d(0, 0px, 0)";
      } else {
        return this.options.selector.style.top = "0";
      }
    };

    return SlideHeader;

  })();

}).call(this);
